### ISSUE TITLE
Feature Request: Search by name or wildcard search by name

### ISSUE THREAD

**Issue by ladytmarie** [open-retirement/open-retirement.github.com#6]
Use one of the two search boxes for a search by name (e.g. name contains Sunnyside).  Limit the number of records returned by this search to 50 or some number that won't impact performance.

**Comment by pjsier** [comment]
@ladytmarie I like this idea, but the Socrata API we're using might be limited. To do a search for containing text, we'd have to use their 'like' function: [reference docs](https://dev.socrata.com/docs/functions/like.html)

Unfortunately, I'm not having much luck using both this, and a filter for results only in Illinois. It doesn't look like I can chain it with something else. I might just be doing it wrong, but if we can filter for Illinois results I'm open to it, but otherwise I think it might just be pulling too many.

**Comment by ladytmarie** [comment]
@pjsier My understanding is that the data set only contains facilities in Illinois/Chicago.  If this is true and you can limit the results to Illinois or a fixed radius/distance from the zipcode, would it be possible?

**Comment by pjsier** [comment]
@ladytmarie so actually the dataset is national (I think the one on the previous version was just Illinois). Here's the [Medicare Dataset](https://data.medicare.gov/Nursing-Home-Compare/Provider-Info/4pq5-n9py). So that's why I'm having trouble with filtering it. It looks like we can't use the `like` function and something to parse the state at the same time, unless I'm formatting it wrong

**Comment by ziegegeist** [comment]
Could we just display all of provider_county_name Cook by default?

**Comment by pjsier** [comment]
@ziegegeist I think that works! I was worried earlier about it being overwhelming, but I tested it out and it seems fine. Just pushed to master and gh-pages

@ladytmarie I think this might actually be a way to do autocomplete for nursing home names. I can load all nursing homes in Cook County, and then search against that sort of the way it's searching against zip codes. Not sure if it'll work, but going to try it because it doesn't seem like the Socrata API will let us do that

**Comment by ladytmarie** [comment]
Cool. Thanks @pjsier

**Comment by pjsier** [comment]
This is implemented in the current version, closing
